### ISSUE TITLE
remove sudo from terraform

### ISSUE THREAD

**Issue by MalloZup** [kubic-project/kubic-init#121]
I'm kind always forget to type the sudo pwd, and i have failures on deploy.

We should remove the sudo, why this is needed? :santa: 

:santa: :mrs_claus: 

:santa: :mrs_claus: 
:santa: :mrs_claus: 
:santa: :mrs_claus: 
:santa: :mrs_claus: 
:santa: :mrs_claus: 
:santa: :mrs_claus: 
:santa: :mrs_claus: 
:santa: :mrs_claus: 
:santa: :mrs_claus: 
:santa: :mrs_claus: 
:santa: :mrs_claus:

**Comment by MalloZup** [comment]
i think `sudo virsh` should not be needed, if it is needed is because the `libvirt_URI` var is not exported .
Imoho we can remove it completely

**Comment by dannysauer** [comment]
You need to be in the `libvirt` group in order to use the `qemu:///system` URI, because it runs commands as root and it'd be bad if anyone on the system could do that.  So removing sudo and switching to the system URI would also require a preceding check to ensure proper group membership.  I'd get behind only using sudo if necessary instead of always assuming "use sudo", though. :)

The test would be to set `LIBVIRT_DEFAULT_URI` and then see if virsh can connect to the `test:///default URI`, and if that connection test fails, try again with sudo.
